from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.imss_engine.publish_insert import PublishBlockedError, publish_imss_aggregate_from_plan


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Publish one IMSS raw aggregate into concentrado using a guarded append-only flow."
    )
    parser.add_argument("--publish-plan", required=True, help="Publish plan JSON generated by plan_imss_publish.py.")
    parser.add_argument(
        "--concentrado-file",
        default=None,
        help="Optional concentrado CSV path; when omitted, the path from the publish plan is used.",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/audit/publish",
        help="Directory for publish manifests, backups, and fresh comparison manifests.",
    )
    args = parser.parse_args()

    try:
        result, manifest_path = publish_imss_aggregate_from_plan(
            args.publish_plan,
            concentrado_file=args.concentrado_file,
            output_dir=args.output_dir,
        )
    except PublishBlockedError as exc:
        payload = {
            "status": "blocked",
            "action": "block",
            "publish_manifest_path": None,
            "result": {
                "status": "blocked",
                "action": "block",
                "validation_status": "blocked",
                "would_write": False,
                "error_message": str(exc),
            },
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        raise SystemExit(1) from exc

    payload = {
        "status": result["status"],
        "action": result["action"],
        "publish_manifest_path": str(manifest_path),
        "result": result,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))

    if result["status"] not in {"success"}:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
