-- Core IMSS tables.
-- This design keeps PostgreSQL as the future local historical master.
-- Version 1 is insert-only: no period overwrite, no full_refresh and no upsert_period.

CREATE TABLE IF NOT EXISTS imss.imss_hechos_asegurados (
    periodo_informacion DATE NOT NULL,
    cve_delegacion TEXT NOT NULL DEFAULT 'no_disponible',
    cve_subdelegacion TEXT NOT NULL DEFAULT 'no_disponible',
    cve_entidad TEXT NOT NULL DEFAULT 'no_disponible',
    cve_municipio TEXT NOT NULL DEFAULT 'no_disponible',
    "tamaño_patron" TEXT NOT NULL DEFAULT 'no_disponible',
    sexo TEXT NOT NULL DEFAULT 'no_disponible',
    rango_edad TEXT NOT NULL DEFAULT 'no_disponible',
    rango_ingreso_vsm TEXT NOT NULL DEFAULT 'no_disponible',
    rango_ingreso_uma TEXT NOT NULL DEFAULT 'no_disponible',
    sector_economico_1 TEXT NOT NULL DEFAULT 'no_disponible',
    sector_economico_2 TEXT NOT NULL DEFAULT 'no_disponible',
    sector_economico_4 TEXT NOT NULL DEFAULT 'no_disponible',
    ptpd TEXT NOT NULL DEFAULT 'no_disponible',

    asegurados NUMERIC NOT NULL DEFAULT 0,
    no_trabajadores NUMERIC NOT NULL DEFAULT 0,
    ta NUMERIC NOT NULL DEFAULT 0,
    ta_sal NUMERIC NOT NULL DEFAULT 0,
    tpu NUMERIC NOT NULL DEFAULT 0,
    tpc NUMERIC NOT NULL DEFAULT 0,
    teu NUMERIC NOT NULL DEFAULT 0,
    tec NUMERIC NOT NULL DEFAULT 0,
    tpu_sal NUMERIC NOT NULL DEFAULT 0,
    tpc_sal NUMERIC NOT NULL DEFAULT 0,
    teu_sal NUMERIC NOT NULL DEFAULT 0,
    tec_sal NUMERIC NOT NULL DEFAULT 0,
    masa_sal_ta NUMERIC NOT NULL DEFAULT 0,
    masa_sal_tpu NUMERIC NOT NULL DEFAULT 0,
    masa_sal_tpc NUMERIC NOT NULL DEFAULT 0,
    masa_sal_teu NUMERIC NOT NULL DEFAULT 0,
    masa_sal_tec NUMERIC NOT NULL DEFAULT 0,
    puestos_permanentes NUMERIC NOT NULL DEFAULT 0,
    puestos_eventuales NUMERIC NOT NULL DEFAULT 0,
    puestos_urbanos NUMERIC NOT NULL DEFAULT 0,
    puestos_campo NUMERIC NOT NULL DEFAULT 0,
    masa_sal_permanentes NUMERIC NOT NULL DEFAULT 0,
    masa_sal_eventuales NUMERIC NOT NULL DEFAULT 0,
    masa_sal_urbanos NUMERIC NOT NULL DEFAULT 0,
    masa_sal_campo NUMERIC NOT NULL DEFAULT 0,
    sbc_total NUMERIC,
    sbc_permanentes NUMERIC,
    sbc_eventuales NUMERIC,
    sbc_urbanos NUMERIC,
    sbc_campo NUMERIC,

    run_id TEXT NOT NULL,
    period_fingerprint_hash TEXT,
    source_url TEXT,
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS imss.imss_staging_asegurados (
    staging_id BIGSERIAL PRIMARY KEY,
    run_id TEXT NOT NULL,
    staging_loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    periodo_informacion DATE,
    cve_delegacion TEXT,
    cve_subdelegacion TEXT,
    cve_entidad TEXT,
    cve_municipio TEXT,
    "tamaño_patron" TEXT,
    sexo TEXT,
    rango_edad TEXT,
    rango_ingreso_vsm TEXT,
    rango_ingreso_uma TEXT,
    sector_economico_1 TEXT,
    sector_economico_2 TEXT,
    sector_economico_4 TEXT,
    ptpd TEXT,

    asegurados NUMERIC,
    no_trabajadores NUMERIC,
    ta NUMERIC,
    ta_sal NUMERIC,
    tpu NUMERIC,
    tpc NUMERIC,
    teu NUMERIC,
    tec NUMERIC,
    tpu_sal NUMERIC,
    tpc_sal NUMERIC,
    teu_sal NUMERIC,
    tec_sal NUMERIC,
    masa_sal_ta NUMERIC,
    masa_sal_tpu NUMERIC,
    masa_sal_tpc NUMERIC,
    masa_sal_teu NUMERIC,
    masa_sal_tec NUMERIC,
    puestos_permanentes NUMERIC,
    puestos_eventuales NUMERIC,
    puestos_urbanos NUMERIC,
    puestos_campo NUMERIC,
    masa_sal_permanentes NUMERIC,
    masa_sal_eventuales NUMERIC,
    masa_sal_urbanos NUMERIC,
    masa_sal_campo NUMERIC,
    sbc_total NUMERIC,
    sbc_permanentes NUMERIC,
    sbc_eventuales NUMERIC,
    sbc_urbanos NUMERIC,
    sbc_campo NUMERIC,

    period_fingerprint_hash TEXT,
    source_url TEXT,
    loaded_at TIMESTAMP,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS imss.imss_period_control (
    periodo_informacion DATE PRIMARY KEY,
    status TEXT NOT NULL,
    row_count BIGINT,
    period_fingerprint_hash TEXT,
    sum_asegurados NUMERIC,
    sum_no_trabajadores NUMERIC,
    sum_ta NUMERIC,
    sum_ta_sal NUMERIC,
    sum_masa_sal_ta NUMERIC,
    run_id TEXT,
    source_url TEXT,
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS imss.imss_run_manifest (
    run_id TEXT PRIMARY KEY,
    run_mode TEXT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    status TEXT,
    config_hash_sha256 TEXT,
    manifest_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
